package com.tradevision.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * The durable record of a pending two-step LIVE-connect confirmation — the token issued by
 * requestLiveConnect's own replica can be confirmed by any replica behind a load balancer,
 * since both methods route through this document rather than an instance-local structure.
 * Holds the credential already encrypted, not plaintext — encryption happens before this
 * document is ever created.
 *
 * An unconfirmed token is removed automatically by a TTL index on expiresAt (Duration.ZERO —
 * MongoDB's documented "expire at this document's own absolute timestamp" behavior, the same
 * mechanism used for ReconciliationLock), so nothing accumulates unconfirmed forever.
 *
 * credentialId here is the future BrokerCredential's own id, pre-generated by
 * requestLiveConnect before encryptedApiKey/encryptedApiSecret are ever encrypted -- not this
 * pending record's own id (token). This lets those two ciphertexts be bound, via AAD, to the
 * exact row they will live in once confirmLiveConnect actually saves the real credential,
 * rather than being encrypted under a context (token) that would stop matching once this
 * pending record is deleted and replaced by the real one.
 */
@Data @NoArgsConstructor
@Document(collection = "pending_live_connects")
public class PendingLiveConnect {
    @Id
    private String token;
    private String userId;
    private BrokerType broker;
    private String credentialId;
    private String encryptedApiKey;
    private String encryptedApiSecret;
    private String keyHint;
    private String accountUid;
    // A real, absolute point in time (not a relative duration from creation) -- backed by a TTL
    // index created via IndexInitializer.ensureTtlIndex(PendingLiveConnect.class, "expiresAt",
    // Duration.ZERO), the same convention ReconciliationLock's own field uses.
    private Instant expiresAt;
}
